### Test the home page endpoint

GET http://localhost:3001/logos

### Test creating a logo after you build the code for adding a logo
POST http://localhost:3001/logos
Content-Type: application/json

{
  "name": "Bunker",
  "description": "The pit of doom",
  "colors": ["tan", "brown"],
  "size": "2.5in x 2.5in"
}

### Test the PUT which should change a logo
PUT http://localhost:3001/logos/5f2c99c1c728050bc2f8ef6b
Content-Type: application/json

{
"name": "Bunker",
  "description": "The pit of doom",
  "colors": ["tan", "brown"],
  "size": "2.5in x 2.5in",
  "updated": true

  }

