### Test the home page endpoint

GET http://localhost:3001/logos

### Test creating a logo after you build the code for adding a logo
POST http://localhost:3001/logos
Content-Type: application/json

{
  "name": "Tiger Woods",
  "description": "Nike symbol over two crossed drivers.",
  "colors": ["black", "red"],
  "size": "2.5in x 2.5in"
}

### Test the PUT which should change a logo
PUT http://localhost:3001/logos/
Content-Type: application/json

{
  "name": "Super Logo"
}
