### Test the types
### types are the product types
# Product types (or product classes) are groups of products which share the same attributes.

# Product attributes contain additional product information, e.g. ISBN, UPC, Brand, which is displayed in storefront and included in product feeds when exporting to marketplaces like Google Shopping, eBay, Amazon ads etc.

GET http://localhost:3001/product-types

### Test creating a type

POST http://localhost:3001/product-types
Content-Type: application/json

{
    "name": "Nike",
    "type": "Apparel"
}

### Test the PUT which should change a type

PUT http://localhost:3001/product-types/5f2f5c3663d83e11cbe355ea
Content-Type: application/json

{
    "name": "Titleist",
    "type": "Gold gear"
}

### Test the DELETE which should delete a type

DELETE http://localhost:3001/product-types/5f2f5bd463d83e11cbe355e9